### ISSUE TITLE
not compatible with 0.4, crash

### ISSUE THREAD

**Issue by gard971** [Albo1125/LSPDFRPlus#3]
Crashes LSPDFR whenever you try to pull a suspect out of a vehicle. You have to remove lspdfr+ from your directory to remove the bug as lspdfr also crashes when using the default menu when lspdfr+ is installed

**Comment by Albo1125** [comment]
Thanks, but you shouldn't be using LSPDFR+ with a version of LSPDFR it's not compatible for. Please don't report bugs if you do.
